### ISSUE TITLE
Postfix (Support for html)

### ISSUE THREAD

**Issue by fedoranvar** [glepnir/prodoc.nvim#2]
At First, thank you for your work.

Secondly,
could you give me a tip how to implement in source code to handle postfix comment (e.g. handling html)?

So, in normal mode it comments whole line 
`<!-- line1 -->`

and for visual mode to comment whole block:
```
<!--
line1
line2
line3
-->
```

**Comment by glepnir** [comment]
there will be have a new api come soon.
